version: '2'

services:
   db:
     build: ./mysql
     volumes:
       - db_data:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: root
   php:
    build: ./php
    ports:
      - '8000:80'
    # restart: always
    volumes:
       - /Users/shashi/Documents/EBT/TestEnvironmentBooking/docker-lamp/logs/:/var/log/apache2/
       - /Users/shashi/Documents/EBT/TestEnvironmentBooking/docker-lamp/ProjectRoot/:/var/www/html
    depends_on:
      - db
volumes:
    db_data:
